### ISSUE TITLE
Обнаружил небольшие баги

### ISSUE THREAD

**Issue by kirillheroes** [Maxsior/color-squares#1]
Мозилла Фаерфокс:
сетка иногда сбивается и последняя строка состоит только из одного квадрата по центру.
На самом браузере игра также немного тупит, почему-то.

Гугл Хром:
при первой игре все 4 квадрата были одинаковыми.
На Мозилла один раз такая же проблема.

Яндекс Браузер:
среди желто-оранжевых квадратов выбрать надо было зелёный (сбился цвет)?
Скорее всего данная проблема также не связана с браузером.

Проблемы, указанные в Мозилла Фаерфокс, скорее всего относятся только к нему, а проблемы у остальных браузеров, предположительно, общие.

**Comment by Maxsior** [comment]
1. Использовал CSS Grid для отображения сетки, теперь не будет сбиваться
2. Исправил баг, когда все квадраты генерировались одинакового цвета
3. Улучшил генерацию цвета, оттенок может немного варьироваться - это нормально.

При генерации цвета попытался использовать [эвклидовую цветоразность в цветовом пространстве sRGB](https://en.wikipedia.org/wiki/Color_difference#sRGB), но почему-то она давала результат хуже, даже в сравнении с первоначальным алгоритмом.

**Comment by Maxsior** [comment]
По производительности нужен более детальный анализ
